name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: windows-latest

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  
