name: build-and-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: [update-content]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest

    # condition to check if triggered by workflow_run and ensure success or check main (Push/Pull)
    # if: >
    #   (github.event_name != 'workflow_run') || 
    #   (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build
        run: |
          cd client
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: client/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: windows-latest

    # # condition for deployment similar to the build job
    # if: >
    #   (github.event_name != 'workflow_run') || 
    #   (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: client/dist
      - name: Set up GitHub PAT as environment variable
        run: echo "GITHUB_PAT=${{ secrets.GITHUB_PAT }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/dist
