name: update-content

on:
  workflow_dispatch:
    inputs:
      content:
        description: Updated JSON content
        required: true
        type: string
      filePath:
        description: Path to the JSON file
        required: true
        type: string
      imageFilePath:
        description: Directory for uploaded images
        required: true
        type: string

jobs:
  update-content:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Write the updated JSON content to the file
      - name: Update JSON file
        run: |
          $content = @"
          ${{ inputs.content }}
          "@
          Set-Content -Path "${{ inputs.filePath }}" -Value $content

      # Step 3: Decode and save base64-encoded images
      - name: Decode and Save Images
        shell: pwsh
        run: |
          # Create the directory if it doesn't exist
          New-Item -ItemType Directory -Force -Path "${{ inputs.imageFilePath }}" | Out-Null

          # Parse JSON content to find image mappings
          $content = Get-Content -Path "${{ inputs.filePath }}" | ConvertFrom-Json
          $content | ForEach-Object {
            $uploadedFiles = $_.uploadedFiles
            if ($uploadedFiles -ne $null) {
              foreach ($fileName in $uploadedFiles.Keys) {
                $base64Content = $uploadedFiles[$fileName]
                $filePath = Join-Path "${{ inputs.imageFilePath }}" $fileName

                # Decode base64 and write to file
                [IO.File]::WriteAllBytes($filePath, [Convert]::FromBase64String($base64Content))
                Write-Host "Saved $fileName to $filePath"
              }
            }
          }

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ${{ inputs.filePath }}
          git add "${{ inputs.imageFilePath }}/*"
          git commit -m "Update content and upload images via GitHub Actions" || echo "No changes to commit"
          git push
