name: update-content

on:
  workflow_dispatch:
    inputs:
      content:
        description: Updated JSON content
        required: true
        type: string
      filePath:
        description: Path to the JSON file
        required: true
        type: string
      imageFilePath:
        description: Directory for uploaded images
        required: false
        type: string

jobs:
  update-content:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Write the updated JSON content to the file
      - name: Update JSON file
        run: |
          $content = @"
          ${{ inputs.content }}
          "@
          Set-Content -Path "${{ inputs.filePath }}" -Value $content

      # Step 3: Upload images if any exist
      - name: Upload new images
        run: |
          mkdir -p "${{ inputs.imageFilePath }}"
          for image in *.webp; do
            [ -f "$image" ] && mv "$image" "${{ inputs.imageFilePath }}"
          done

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ${{ inputs.filePath }}
          git add ${{ inputs.imageFilePath }}
          git commit -m "Update content and upload images via GitHub Actions" || echo "No changes to commit"
          git push
